### ISSUE TITLE
 Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by SamDecrock** [chbrown/pdfi#1]
Ok,

This is what I get when I require() your module:

```
TypeError: Cannot read property 'prototype' of undefined
    at __extends (/some/awesome/project/node_modules/pdfi/PDF.js:4:21)
    at /some/awesome/project/node_modules/pdfi/PDF.js:15:5
    at Object.<anonymous> (/some/awesome/project/node_modules/pdfi/PDF.js:21:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/some/awesome/project/node_modules/pdfi/index.js:7:11)
```

So I can't get beyond the first line of code :p

**Comment by chbrown** [comment]
I figured this is fixed by now :/
